### ISSUE TITLE
can't build on windows

### ISSUE THREAD

**Issue by sam0x17** [parro-it/libui-node#56] opened 2018-01-01 20:19 UTC
I am having an interesting error. On windows 10 under node 8.9.3 (I've also tried 6.9.2) if I `npm install` on a project that uses `libui-node` everything compiles correctly, but then when I go to run I get:

```
node .
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\sam\Desktop\bitfort-client\node_modules\libui-node\build\Release\nbind.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at initNode (C:\Users\sam\Desktop\bitfort-client\node_modules\nbind\dist\nbind.js:162:15)
    at C:\Users\sam\Desktop\bitfort-client\node_modules\nbind\dist\nbind.js:130:13
    at findCompiledModule (C:\Users\sam\Desktop\bitfort-client\node_modules\nbind\dist\nbind.js:94:13)
    at find (C:\Users\sam\Desktop\bitfort-client\node_modules\nbind\dist\nbind.js:108:13)
    at Object.init (C:\Users\sam\Desktop\bitfort-client\node_modules\nbind\dist\nbind.js:119:5)
    at Object.<anonymous> (C:\Users\sam\Desktop\bitfort-client\node_modules\libui-node\index.js:3:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

Interestingly, if I move `node_modules/libui-node/build/Release/nbind.node` to `node_modules/libui-node/`, it will run correctly, however then I get problems when I try to export this with `pkg` (e.g. complaints about the file nbind.node not self-registering as a module). What is the proper way to fix this @parro-it?

Thanks!!

**Comment by sam0x17** [comment] 2018-01-07 23:11
any headway on this? I'd be happy to help if I can

**Comment by sam0x17** [comment] 2018-01-28 20:35
@parro-it any luck with this? I can provide a test windows VM for you to remote into if that would help.

**Comment by parro-it** [comment] 2018-02-19 19:35
Next version (that will be coming next weeks) will support it.
In the meanwhile, @kusti8 solve it to use it in proton-native: https://github.com/kusti8/libui-node/blob/master/copy_node.js

**Comment by parro-it** [comment] 2018-02-19 19:39
I close this because is a duplicate of #46

**Closed by parro-it** 2018-02-19 19:39 UTC
