### ISSUE TITLE
Startup time is slow for example programs

### ISSUE THREAD

**Issue by joelewing** [parro-it/libui-node#47] opened 2016-08-09 22:54 UTC
I haven't started creating my own programs with this library, but I've tried the examples and run in to a major disappointment.  The Control Gallery example and the Core Api example both take a really long time to start (over a minute!).  Is this a bug in the examples, the library or am I doing something wrong?

node version: v6.3.1
hardware: i5, 8GB of RAM

**Comment by PaulBGD** [comment] 2016-08-13 15:35
What platform and architecture?

**Comment by physicsshark** [comment] 2016-08-13 15:58
Linux, x86_64.

**Comment by parro-it** [comment] 2016-08-20 07:03
@physicsshark, I noticed that in last release you have to type `CTRL` key in console to make the GUI show. I don't yet have discovered what's the cause, but try this hack, maybe it solve this issue...

Also, what linux distribution are you using?

**Comment by physicsshark** [comment] 2016-09-03 16:45
Linux Mint 18, which is based on Ubuntu 16.04.

**Comment by szkrd** [comment] 2016-11-21 08:37
Same here, Arch x86_64. Some, but not all demos are very slow to start, more then ten seconds.

**Comment by zangloo** [comment] 2017-09-20 02:39
need press any modifier key to start program faster.
and in examples, using 
`libui.Ui.main();`
instead of
`libui.stopLoop();`
fix the problem.

**Comment by zaniar** [comment] 2017-11-09 13:57
@zangloo I think you mean using `libui.Ui.main()` & `libui.Ui.quit` instead of `libui.startLoop()` & `libui.stopLoop()`.

I also confirm that it fix the slow startup.

**Comment by parro-it** [comment] 2018-03-19 19:49
This should be fixed in version 0_1_0. @joelewing please reopen if still in trouble

**Closed by parro-it** 2018-03-19 19:49 UTC
